<?php

namespace App\Support;

use App\Models\Agent;

class NotificationMessageResolver
{
    private static array $greenMessages = [
        'Agent1' => 'All systems normal. ✅',
        'Agent2' => 'Maintain current course. ✅',
        'Agent3' => 'Proceed as planned. ✅',
        'Agent4' => 'Route is clear. ✅',
        'Agent5' => 'No issues reported. ✅',
        'Agent6' => 'Travel safe. ✅',
        'Agent7' => 'Continue forward. ✅',
        'Agent8' => 'Green path ahead. ✅',
        'Agent9' => 'Operationally sound. ✅',
        'Agent10' => 'Smooth driving expected. ✅',
        'Agent11' => 'Maintain current course. ✅',
        'Agent12' => 'All systems normal. ✅',
        'Agent13' => 'Proceed as planned. ✅',
        'Agent14' => 'Travel safe. ✅',
        'Agent15' => 'Route is clear. ✅',
        'Agent16' => 'No issues reported. ✅',
        'Agent17' => 'Continue forward. ✅',
        'Agent18' => 'Operationally sound. ✅',
        'Agent19' => 'Green path ahead. ✅',
        'Agent20' => 'Smooth driving expected. ✅',
        'Agent21' => 'Maintain current course. ✅',
        'Agent22' => 'All systems normal. ✅',
        'Agent23' => 'Proceed as planned. ✅',
        'Agent24' => 'Route is clear. ✅',
        'Agent25' => 'No issues reported. ✅',
        'Agent26' => 'Travel safe. ✅',
        'Agent27' => 'Continue forward. ✅',
        'Agent28' => 'Green path ahead. ✅',
        'Agent29' => 'Operationally sound. ✅',
        'Agent30' => 'Smooth driving expected. ✅',
        'Agent31' => 'Maintain current course. ✅',
        'Agent32' => 'All systems normal. ✅',
        'Agent33' => 'Proceed as planned. ✅',
        'Agent34' => 'Travel safe. ✅',
        'Agent35' => 'Route is clear. ✅',
        'Agent36' => 'No issues reported. ✅',
        'Agent37' => 'Continue forward. ✅',
        'Agent38' => 'Operationally sound. ✅',
        'Agent39' => 'Green path ahead. ✅',
        'Agent40' => 'Smooth driving expected. ✅',
        'Agent41' => 'Maintain current course. ✅',
        'Agent42' => 'All systems normal. ✅',
        'Agent43' => 'Proceed as planned. ✅',
        'Agent44' => 'Travel safe. ✅',
        'Agent45' => 'Route is clear. ✅',
        'Agent46' => 'No issues reported. ✅',
        'Agent47' => 'Continue forward. ✅',
        'Agent48' => 'Operationally sound. ✅',
        'Agent49' => 'Green path ahead. ✅',
        'Agent50' => 'Smooth driving expected. ✅',
    ];

    private static array $redMessages = [
        'Agent1' => 'Accident ahead. Proceed with caution. ⚠️',
        'Agent2' => 'Heavy traffic. Expect delays. ⚠️',
        'Agent3' => 'Roadblock detected. Consider alternate route. ⚠️',
        'Agent4' => 'Obstruction ahead. Slow down. ⚠️',
        'Agent5' => 'Major incident reported. Avoid the area. ⚠️',
        'Agent6' => 'Hazardous conditions. Drive carefully. ⚠️',
        'Agent7' => 'Emergency response in progress. Stay clear. ⚠️',
        'Agent8' => 'Dangerous zone ahead. Reduce speed. ⚠️',
        'Agent9' => 'High-risk area. Proceed slowly. ⚠️',
        'Agent10' => 'Road closed ahead. Reroute immediately. ⚠️',
        'Agent11' => 'Sudden stop ahead. Brake gently. ⚠️',
        'Agent12' => 'Unusual activity detected. Remain alert. ⚠️',
        'Agent13' => 'Collision site up ahead. Caution advised. ⚠️',
        'Agent14' => 'Congestion reported. Expect hold-up. ⚠️',
        'Agent15' => 'Road hazard ahead. Reduce speed. ⚠️',
        'Agent16' => 'Flooded roadway. Seek alternate path. ⚠️',
        'Agent17' => 'Icy conditions reported. Drive cautiously. ⚠️',
        'Agent18' => 'Debris on the road. Stay vigilant. ⚠️',
        'Agent19' => 'Sudden lane closure ahead. ⚠️',
        'Agent20' => 'Emergency crews on site. Yield and proceed slowly. ⚠️',
        'Agent21' => 'Visibility low. Use headlights and caution. ⚠️',
        'Agent22' => 'Sudden slowdown reported. Stay back. ⚠️',
        'Agent23' => 'Expect delays. Roadwork in progress. ⚠️',
        'Agent24' => 'Dangerous curve ahead. Reduce speed. ⚠️',
        'Agent25' => 'Oversize load in area. Keep distance. ⚠️',
        'Agent26' => 'Multi-car collision ahead. Stay alert. ⚠️',
        'Agent27' => 'Signal outage reported. Proceed carefully. ⚠️',
        'Agent28' => 'Bridge maintenance ahead. Caution required. ⚠️',
        'Agent29' => 'Flashing red light. Stop before proceeding. ⚠️',
        'Agent30' => 'Slippery road. Slow down. ⚠️',
        'Agent31' => 'Yield to emergency responders. ⚠️',
        'Agent32' => 'Lane restriction in effect. Merge early. ⚠️',
        'Agent33' => 'Road narrows ahead. Prepare to merge. ⚠️',
        'Agent34' => 'Shoulder closed. Stay in lane. ⚠️',
        'Agent35' => 'Accident cleanup in progress. Expect delay. ⚠️',
        'Agent36' => 'Emergency declared in area. Follow instructions. ⚠️',
        'Agent37' => 'Downed power line. Stay away. ⚠️',
        'Agent38' => 'Turnaround ahead. Prepare to detour. ⚠️',
        'Agent39' => 'Unstable road conditions. Drive with care. ⚠️',
        'Agent40' => 'Stop-and-go traffic. Maintain space. ⚠️',
        'Agent41' => 'Blocked intersection ahead. ⚠️',
        'Agent42' => 'High winds. Secure loose items. ⚠️',
        'Agent43' => 'Limited access. Prepare to stop. ⚠️',
        'Agent44' => 'Emergency sirens active. Be alert. ⚠️',
        'Agent45' => 'Construction debris ahead. ⚠️',
        'Agent46' => 'Emergency lane closed. ⚠️',
        'Agent47' => 'Seek alternate highway route. ⚠️',
        'Agent48' => 'Enforcement checkpoint ahead. ⚠️',
        'Agent49' => 'Obstructed signage. Stay alert. ⚠️',
        'Agent50' => 'Do not enter zone ahead. Restricted access. ⚠️',
    ];

    private static array $yellowMessages = [
        'Agent1' => 'Temporary slow zone ahead. 🟠',
        'Agent2' => 'Proceed with caution. 🟠',
        'Agent3' => 'Lane merge ahead. 🟠',
        'Agent4' => 'Light construction zone. 🟠',
        'Agent5' => 'Reduced speed advised. 🟠',
        'Agent6' => 'Upcoming curve. Use caution. 🟠',
        'Agent7' => 'Watch for changing conditions. 🟠',
        'Agent8' => 'Caution: pedestrian activity possible. 🟠',
        'Agent9' => 'Prepare for intermittent delays. 🟠',
        'Agent10' => 'Minor roadwork ahead. 🟠',
        'Agent11' => 'Stay alert for lane shifts. 🟠',
        'Agent12' => 'Uneven pavement detected. 🟠',
        'Agent13' => 'Proceed through narrow passage. 🟠',
        'Agent14' => 'Loose gravel. Reduce speed. 🟠',
        'Agent15' => 'Traffic light timing irregular. 🟠',
        'Agent16' => 'Animal crossing zone. 🟠',
        'Agent17' => 'Mild congestion reported. 🟠',
        'Agent18' => 'Intermittent stops expected. 🟠',
        'Agent19' => 'Expect minor delays. 🟠',
        'Agent20' => 'Temporary signage in place. 🟠',
        'Agent21' => 'Reduced visibility zone. 🟠',
        'Agent22' => 'Crosswalk area. Stay cautious. 🟠',
        'Agent23' => 'Monitor surrounding vehicles. 🟠',
        'Agent24' => 'Yield where necessary. 🟠',
        'Agent25' => 'Slippery patch possible. 🟠',
        'Agent26' => 'Prepare for roundabout. 🟠',
        'Agent27' => 'Drizzle reported. Slow down. 🟠',
        'Agent28' => 'Road paint fresh. Avoid swerving. 🟠',
        'Agent29' => 'Pavement testing in progress. 🟠',
        'Agent30' => 'Sidewalk work near curb. 🟠',
        'Agent31' => 'Minor detour in place. 🟠',
        'Agent32' => 'Temporary markers present. 🟠',
        'Agent33' => 'Parked vehicles on shoulder. 🟠',
        'Agent34' => 'Use low beam headlights. 🟠',
        'Agent35' => 'Be ready to stop if signaled. 🟠',
        'Agent36' => 'School zone nearby. 🟠',
        'Agent37' => 'Lane coloring inconsistent. 🟠',
        'Agent38' => 'Signal timing test ongoing. 🟠',
        'Agent39' => 'Mild road dip ahead. 🟠',
        'Agent40' => 'Caution: potholes reported. 🟠',
        'Agent41' => 'Fog patch ahead. 🟠',
        'Agent42' => 'Occasional lane change necessary. 🟠',
        'Agent43' => 'Roadside maintenance observed. 🟠',
        'Agent44' => 'Narrow bridge ahead. 🟠',
        'Agent45' => 'Shared turn lane ahead. 🟠',
        'Agent46' => 'Unmarked intersection coming. 🟠',
        'Agent47' => 'Surface water possible. 🟠',
        'Agent48' => 'Reduced lighting conditions. 🟠',
        'Agent49' => 'Delays may vary. 🟠',
        'Agent50' => 'Keep safe distance. 🟠',
    ];

    public static function resolve(Agent $agent): string
    {
        $code = $agent->code;

        return match ($agent->state) {
            // 'G' => self::$greenMessages[$code],
            // 'R' => self::$redMessages[$code],
            // 'Y' => self::$yellowMessages[$code],

            'G' => self::$greenMessages[$code] ?? '✅ All clear, but specific message not found.',
            'R' => self::$redMessages[$code] ?? '⚠️ Warning: Details not found.',
            'Y' => self::$yellowMessages[$code] ?? '🟠 Caution: Message missing.',
            default => 'ℹ️ Unknown state. Proceed carefully.',
        };
    }
}
